# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               James E. Pustejovsky
tagline:             'University of Texas at Austin'
description:         
url:                 http://jepusto.github.io
baseurl:             'http://jepusto.github.io'
paginate:            10

gems: [jekyll-paginate]

# About/contact
author:
  name:              James E. Pustejovsky
  url:               
  email:             pusto@austin.utexas.edu
  twitter:           jepusto
  github:            jepusto

# Disqus comments configuration (leave blank to disable comments)
disqus_shortname: 'jepusto'

# Custom vars
version:             1.0.0

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: pages   # limit to pages
    values:
      is_page: true # automatically set is_page=true for all pages