# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               James E. Pustejovsky
tagline:             'University of Texas at Austin'
description:         
url:                 http://jepusto.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              James E. Pustejovsky
  url:               
  email:             pusto@austin.utexas.edu

# Custom vars
version:             1.0.0
